spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# This app properties
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: ${JWT_EXPIRATION_IN_MS}